# Generated by Django 4.2.3 on 2023-07-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='one_off',
            field=models.BooleanField(default=False),
        ),
    ]
