# Generated by Django 4.2.3 on 2023-07-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_competition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='likes',
        ),
        migrations.AddField(
            model_name='competition',
            name='likes',
            field=models.ManyToManyField(to='manager.listener'),
        ),
    ]
