# Generated by Django 4.2.3 on 2023-07-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_competition_dislikes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='social_links',
            new_name='social_accounts',
        ),
        migrations.AddField(
            model_name='competition',
            name='share_link',
            field=models.CharField(default=1, max_length=3000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competition',
            name='dislikes',
            field=models.ManyToManyField(related_name='dislikes', to='manager.listener'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='manager.listener'),
        ),
    ]
