# Generated by Django 4.2.3 on 2023-07-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_rename_social_links_competition_social_accounts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to='manager.listener'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='manager.listener'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='social_accounts',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
