# Generated by Django 4.2.3 on 2023-07-20 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_alter_competition_dislikes_alter_competition_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
