# Generated by Django 4.2.3 on 2023-07-20 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_alter_competition_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
