# Generated by Django 4.2.3 on 2023-07-20 11:55

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_alter_competition_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=1000)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('thumb', models.ImageField(default='default.jpg', upload_to='pics')),
                ('audio', models.FileField(upload_to='audio_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])])),
                ('one_off', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=500)),
            ],
        ),
    ]
