# Generated by Django 4.2.3 on 2023-07-20 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_alter_podcast_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='com_dislikes', to='manager.listener'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='com_likes', to='manager.listener'),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=1000)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('thumb', models.ImageField(default='default.jpg', upload_to='pics')),
                ('share_link', models.CharField(max_length=3000)),
                ('social_accounts', models.CharField(blank=True, max_length=1000)),
                ('slug', models.SlugField(blank=True, max_length=500)),
                ('dislikes', models.ManyToManyField(blank=True, related_name='blog_dislikes', to='manager.listener')),
                ('likes', models.ManyToManyField(blank=True, related_name='blog_likes', to='manager.listener')),
            ],
        ),
    ]
