# Generated by Django 4.2.3 on 2023-07-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_alter_competition_dislikes_alter_competition_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='end_date',
        ),
    ]
