# Generated by Django 4.2.3 on 2023-07-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_remove_blog_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='share_link',
            field=models.CharField(default='home.html', max_length=3000),
        ),
        migrations.AlterField(
            model_name='competition',
            name='share_link',
            field=models.CharField(default='home.html', max_length=3000),
        ),
    ]
