# Generated by Django 4.2.3 on 2023-07-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_alter_blog_share_link_alter_competition_share_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
