# Generated by Django 4.2.3 on 2023-07-21 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_alter_blog_thumb_alter_competition_thumb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumb',
            field=models.ImageField(default='default.jpg', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='thumb',
            field=models.ImageField(default='default.jpg', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='audio',
            field=models.FileField(upload_to='audio_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'm4a', 'wav'])]),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='thumb',
            field=models.ImageField(default='default.jpg', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='program',
            name='thumb',
            field=models.ImageField(default='default.jpg', upload_to='pics'),
        ),
    ]
