# Generated by Django 4.2.3 on 2023-07-22 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0024_alter_blog_thumb_alter_competition_thumb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=1000)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('thumb', models.ImageField(default='default.jpg', upload_to='pics')),
                ('share_link', models.CharField(default='home.html', max_length=3000)),
                ('social_accounts', models.CharField(blank=True, max_length=1000)),
                ('slug', models.SlugField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='LocalNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=1000)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('thumb', models.ImageField(default='default.jpg', upload_to='pics')),
                ('share_link', models.CharField(default='home.html', max_length=3000)),
                ('social_accounts', models.CharField(blank=True, max_length=1000)),
                ('slug', models.SlugField(blank=True, max_length=500)),
            ],
        ),
        migrations.RenameModel(
            old_name='Blog',
            new_name='Announcement',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Podcast',
        ),
        migrations.DeleteModel(
            name='Competition',
        ),
    ]
