# Generated by Django 4.2.3 on 2023-07-22 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0025_globalnew_localnew_rename_blog_announcement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='likes',
        ),
    ]
