# Generated by Django 4.2.3 on 2023-07-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0027_alter_announcement_thumb_alter_globalnew_thumb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalnew',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='localnew',
            name='end_date',
        ),
        migrations.AlterField(
            model_name='globalnew',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='localnew',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
