# Generated by Django 4.2.3 on 2023-07-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0028_remove_globalnew_end_date_remove_localnew_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='thumb',
            field=models.ImageField(default='default.jpg', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='globalnew',
            name='thumb',
            field=models.ImageField(default='default.jpg', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='localnew',
            name='thumb',
            field=models.ImageField(default='default.jpg', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='program',
            name='thumb',
            field=models.ImageField(default='default.jpg', upload_to='pics'),
        ),
    ]
