# Generated by Django 4.2.3 on 2023-07-24 11:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0029_alter_announcement_thumb_alter_globalnew_thumb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='thumb',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='globalnew',
            name='thumb',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='localnew',
            name='thumb',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='program',
            name='thumb',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image'),
        ),
    ]
